services:
  db:
    container_name: go_pgadmin
    image: postgres:latest
    restart: always
    container_name: go_postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: go_yuhhe&87GHKfd
      POSTGRES_USER: go_user
      PGADMIN_DEFAULT_EMAIL: heronhurpia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: go_password
volumes:
  postgres-data: