services:

  postgres:
    image: postgres:latest        # Use the latest official PostgreSQL image
    container_name: db            # Assign a meaningful name
    restart: unless-stopped       # Restart unless explicitly stopped
    environment:
      POSTGRES_PASSWORD: strong_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5430:5430"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Define a volume to persist PostgreSQL data
volumes:
  postgres_data:

